Repository gbowne1/codebooker, pull requests merged in 2023-08, with the labels that each got.

#110 login/implemented
  src/components/Register/Register.jsx
  src/pages/Login/Login.jsx
  src/server/controller/userController.js
  src/server/index.js
  src/server/package-lock.json
  src/server/package.json
  src/server/routes/userRoutes.js
Labels: bug

#116 implement/protectedroutes
  package-lock.json
  package.json
  src/App.js
  src/ProtectedRoute.jsx
  src/components/BookSearch/BookSearch.css
  src/components/Library/Library.jsx
  src/pages/Login/Login.jsx
  src/server/controller/booksController.js
  src/server/controller/userController.js
  src/server/index.js
Labels: bug, enhancement, frontend

#117 Style the login and register page
  src/components/Register/Register.css
  src/components/Register/Register.jsx
  src/pages/Login/Login.css
  src/pages/Login/Login.jsx
Labels: enhancement, frontend

#125 Added fork and clone instructions with images
  docs/CreateFork.png
  docs/CreateForkBtn.png
  docs/ForkClone.md
  docs/ForkedBranch.png
  docs/fork.png
Labels: documentation

#136 Feature/forgot password
  src/App.js
  src/components/Register/Register.css
  src/pages/ForgotPassword/ForgotPassword.css
  src/pages/ForgotPassword/ForgotPassword.jsx
  src/pages/ResetPassword/ResetPassword.css
  src/pages/ResetPassword/ResetPassword.jsx
  src/server/controller/userController.js
  src/server/model/tokenModel.js
  src/server/package-lock.json
  src/server/package.json
  src/server/routes/userRoutes.js
Labels: enhancement, frontend

#140 Clicking logout button fix
  package-lock.json
  package.json
  src/components/Dropdown/Dropdown.js
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/server/.variable.env
  src/server/package-lock.json
Labels: enhancement, help wanted

#142 Fix bug: Category field wrongly populates 'Author' column in book addition form
  src/components/Library/Library.jsx
Labels: bug

#144 remove/warnings
  docs/ForkClone.md
  src/components/Register/Register.css
  src/pages/ForgotPassword/ForgotPassword.css
  src/pages/ForgotPassword/ForgotPassword.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.css
  src/pages/ResetPassword/ResetPassword.jsx
  src/server/controller/userController.js
  src/server/model/tokenModel.js
  src/server/package-lock.json
  src/server/routes/userRoutes.js
Labels: bug

#146 User profile page
  src/App.js
  src/components/Dropdown/Dropdown.js
  src/pages/Home/Home.jsx
  src/pages/Profile/Profile.jsx
  src/server/.variable.env
  src/server/package-lock.json
Labels: enhancement, help wanted, frontend

#147 Fixing .variable-env and Home.jsx component
  src/pages/Home/Home.jsx
  src/server/.variable.env
Labels: bug

#151 feedback/model
  src/server/controller/feedBackController.js
  src/server/model/feedBackModel.js
  src/server/routes/userRoutes.js
Labels: enhancement

#153 feature: added privacy-policy page
  src/App.js
  src/components/Dropdown/Dropdown.js
  src/pages/PrivacyPolicy/PrivacyPolicy.css
  src/pages/PrivacyPolicy/PrivacyPolicy.jsx
Labels: enhancement

#154 Feature/adding new book to db
  src/components/Library/Library.css
  src/components/Library/Library.jsx
  src/server/controller/booksController.js
  src/server/model/booksModel.js
  src/server/routes/booksRoutes.js
Labels: enhancement, frontend

#158 fragment issue fixed
  src/components/Dropdown/Dropdown.js
  src/pages/userDetails/UserDetails.jsx
  src/server/.variable.env
Labels: bug
