Repository gbowne1/codebooker, pull requests merged in 2023-11, with the labels that each got.

#198 Update title and description
  public/index.html
Labels: bug, enhancement, frontend

#199 Add-a-create-profile-feature
  package-lock.json
  package.json
  public/Assets/Avatar.webp
  public/Assets/avatar-img.png
  public/Assets/profile-banner-img.png
  src/components/FormikContainer/CreateProfileForm/CreateProfileForm.css
  src/components/FormikContainer/CreateProfileForm/CreateProfileForm.jsx
  src/components/FormikContainer/CreateProfileForm/IDE_Options.js
  src/components/FormikContainer/CreateProfileForm/SelectInputField.jsx
  src/components/FormikContainer/CreateProfileForm/locationOptions.js
  src/components/FormikContainer/CreateProfileForm/operatingSystemOptions.js
  src/components/FormikContainer/CreateProfileForm/programingSkillOptions.js
  src/components/Library/Library.css
  src/components/Library/Library.jsx
  src/pages/Home/Home.jsx
  src/pages/Profile/CreateProfileAlert.css
  src/pages/Profile/CreateProfileAlert.jsx
  src/pages/Profile/Profile.css
  src/pages/Profile/Profile.jsx
  src/server/controller/profileController.js
  src/server/index.js
  src/server/model/profileModel.js
  src/server/routes/profileRoutes.js
Labels: enhancement, help wanted, feature request, needs-review, design

#203 Style policy privacy page
  src/pages/PrivacyPolicy/PrivacyPolicy.css
  src/pages/PrivacyPolicy/PrivacyPolicy.jsx
Labels: enhancement, frontend, code-review, needs-review, css, design
