Repository gbowne1/codebooker, pull requests merged in 2023-04, with the labels that each got.

#9 Sidebar added using <Drawer /> from MUI v5.11.6
  src/App.js
  src/components/SideNav/SideNav.css
  src/components/SideNav/SideNav.jsx
Labels: enhancement, help wanted, good first issue

#17 adding new contributors to contrib doc
  CONTRIBUTORS.md
Labels: documentation, enhancement

#18 This commit fixes the incorrect GitHub marker link
  CONTRIBUTORS.md
Labels: bug

#20 #13 Resolved
  src/App.js
  src/components/SettingIcon/Setting.css
  src/components/SettingIcon/Setting.jsx
Labels: enhancement, help wanted
