Repository gbowne1/codebooker, pull requests merged in 2023-10, with the labels that each got.

#191 Edited the Devsetup.md file
  docs/Clone.png
  docs/DEVSETUP.md
  docs/ForkClone.md
Labels: documentation

#192 Feature/ignore files
  .eslintignore
  .prettierignore
  CONTRIBUTING.md
  docs/DEVSETUP.md
  docs/ForkClone.md
  src/server/README.md
  src/tests/signup.test.js
Labels: enhancement, code-review, needs-review

#195 Get books from file and seed database when DB is empty
  src/components/Library/Library.jsx
  src/components/Library/data.json
  src/server/controller/booksController.js
  src/server/routes/booksRoutes.js
Labels: bug, enhancement, help wanted, feature request, performance, code-review, needs-review

#196 Fix/css: Remove font-smooth styling
  src/index.css
Labels: css
