Repository gbowne1/codebooker, pull requests merged in 2023-09, with the labels that each got.

#161 Bug/fix library jsx use effect issues
  src/components/Library/Library.jsx
  src/pages/Home/Home.jsx
Labels: bug

#166 Feat/add a help feature
  package-lock.json
  package.json
  src/App.js
  src/components/Dropdown/Dropdown.js
  src/components/FormikContainer/SupportForm/SupportForm.js
  src/pages/Support/Support.css
  src/pages/Support/Support.jsx
  src/server/controller/supportController.js
  src/server/index.js
  src/server/model/supportModel.js
  src/server/routes/supportRoutes.js
Labels: frontend, feature request, code-review

#169 Feature/capture feedback
  package-lock.json
  package.json
  src/components/Dropdown/Dropdown.js
  src/components/Feedback/CaptureFeedback.jsx
  src/components/Feedback/DirectFeedback.jsx
  src/components/Feedback/EmailFeedback.jsx
  src/components/Feedback/Feedback.css
  src/server/.variable.env
  src/server/controller/feedBackController.js
  src/server/controller/userController.js
  src/server/package.json
  src/server/routes/userRoutes.js
Labels: enhancement, frontend, feature request, code-review, needs-review

#175 Fix Duplicate Login Prompt
  src/pages/Home/Home.jsx
Labels: devops, performance, needs-review, critical

#173 Feat/add tailwindcss on top of mui
  package-lock.json
  package.json
  postcss.config.js
  src/components/BookSearch/BookSearch.css
  src/index.css
  src/index.js
  tailwind.config.js
Labels: enhancement, frontend, usability, code-review, needs-review

#177 Fix: `Home.jsx` and `Library.jsx` useEffect hook missing dependency issue
  src/components/Library/Library.jsx
  src/pages/Home/Home.jsx
Labels: bug, frontend, code-review, needs-review

#178 Added new recommendations
  src/components/Library/data.json
Labels: code-review, needs-review

#180 jestTest/init
  package.json
  postcss.config.js
  src/App.test.js
  src/components/BookSearch/BookSearch.css
  src/components/Feedback/CaptureFeedback.jsx
  src/components/Feedback/Feedback.css
  src/components/Library/Library.css
  src/pages/PrivacyPolicy/PrivacyPolicy.css
  src/pages/Support/Support.css
  src/server/controller/booksController.js
  src/server/controller/supportController.js
  src/server/controller/userController.js
  src/server/model/booksModel.js
  src/server/model/supportModel.js
  src/server/routes/booksRoutes.js
  src/server/routes/supportRoutes.js
  src/tests/App.test.js
  src/tests/home.test.js
  src/tests/login.test.js
  tailwind.config.js
Labels: enhancement, devops, code-review, needs-review

#181 Feature/registration redirect
  src/components/Register/Register.jsx
  src/server/controller/feedBackController.js
  src/server/controller/userController.js
Labels: enhancement

#183 Update to the contributing.md file
  CONTRIBUTING.md
  README.md
  TODO.md
Labels: documentation, code-review, needs-review

#186 Updated HTML document for /privacy-policy page
  src/pages/PrivacyPolicy/PrivacyPolicy.jsx
  src/server/index.js
Labels: frontend, code-review, needs-review

#189 Unit Test: Login and Signup
  package-lock.json
  package.json
  src/App.js
  src/components/Register/Register.jsx
  src/pages/Login/Login.jsx
  src/server/controller/feedBackController.js
  src/server/controller/userController.js
  src/setupTests.js
  src/tests/login.test.js
  src/tests/mocks/handlers.js
  src/tests/mocks/server.js
  src/tests/signup.test.js
Labels: enhancement, code-review, needs-review, Testing

#190 added docker-compose.yml, updated server README
  src/server/README.md
  src/server/setup/cleanup.sh
  src/server/setup/docker-compose.yml
  src/server/setup/setup.sh
Labels: devops, code-review, needs-review
