Repository gbowne1/codebooker, pull requests merged in 2024-03, with the labels that each got.

#216 [Todo] Add to Library button #63
  src/components/Library/Library.jsx
  src/components/Library/Library.module.css
  src/server/controller/booksController.js
  src/server/model/userBooksLibraryModel.js
  src/server/routes/booksRoutes.js
Labels: enhancement, frontend, feature request, code-review, needs-review

#219 Profile fix and API documentation
  README.md
  docs/CodeBooker-API-Doc.yml
  package-lock.json
  package.json
  src/server/controller/profileController.js
  src/server/model/profileModel.js
Labels: enhancement, code-review, backend

#215 FIX : 213 | removed the empty rependency array from useEffect for fetching books
  src/components/Library/Library.jsx
Labels: bug
